---
repos:
  - repo: https://github.com/ansible-network/collection_prep
    rev: 1.1.2
    hooks:
      # - id: autoversion # removed as being handled by GHA push and release drafter
      - id: update-docs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
